image: gitlab/dind

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - cd src
    - 'docker build -t $CI_REGISTRY:$CI_PIPELINE_IID -t $CI_REGISTRY:latest .'
    - 'docker push $CI_REGISTRY'
    