version: '3.8'
 

services:
  web:
    image: mydockerapiotus
    depends_on:
      - postgres_image
    build:
      context: .
      dockerfile: Otus.Teaching.PromoCodeFactory.WebHost/Dockerfile
    ports:
      - 3000:3000     
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:3000
     - DB_CONNECTION_STRING=host=postgresql-13;port=5432;database=blogdb;username=postgres;password=5tgbh22qA
  
  postgres_image:
    image: postgres:13.0
    container_name: postgresql-13
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5tgbh22qA"
      POSTGRES_DB: "blogdb"