version: '3.4'

services:
  otus.teaching.promocodefactory.webhost:
    image: ${DOCKER_REGISTRY-}otusteachingpromocodefactorywebhost
    build:
      context: .
      dockerfile: Otus.Teaching.PromoCodeFactory.WebHost\Dockerfile